routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'User'], function () {
    Route::get('/', 'HomeController@index')->name('welcome');

    Route::get('/article/{article?}', 'ArticleController@article')->name('article');

    Route::get('/article/tag/{tag?}', 'HomeController@tag')->name('tag');

    Route::get('/article/category/{category?}', 'HomeController@category')->name('category');
});

Route::group(['namespace' => 'Admin'], function () {
    Route::get('administration/home', 'HomeController@index')->name('admin.home');

    Route::resource('administration/user', 'UserController');

    Route::resource('administration/adminUser', 'AdminUserController');

    Route::resource('administration/role', 'RoleController');

    Route::resource('administration/article', 'ArticleController');

    Route::resource('administration/tag', 'TagController');

    Route::resource('administration/category', 'CategoryController');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'title', 'subtitle', 'body'
    ];

    public function userCreated()
    {
        return $this->belongsTo('App\User', 'created_by');
    }

    public function userUpdated()
    {
        return $this->belongsTo('App\User', 'updated_by');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'article_tags')->withTimestamps();
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category', 'article_categories')->withTimestamps();
    }

    public function getRouteKeyName()
    {
        return 'id';
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\admin;

use App\AdminUser;
use App\Article;
use App\Category;
use App\Http\Controllers\Controller;
use App\Tag;
use App\User;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ArticleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::forUser(Auth::user())->allows('articles.create')) {
            $tags = Tag::all();
            $categories = Category::all();
            return view('admin.articles.article', compact(['tags', 'categories']));
        }

        return redirect(route('admin.home'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'subtitle' => 'required',
            'body' => 'required',
            'image' => 'required'
        ]);

        //Article::create($request->all());

        $article = new Article();
        $article->title = $request->title;
        $article->subtitle = $request->subtitle;
        $article->body = $request->body;
        if ($request->hasFile('image')) {
            $fileName  = $request->image->getClientOriginalName();
            $request->image->storeAs('images', $fileName, 'public');
            $article->image = $fileName;
        }
        $article->status = $request->status ? $request->status : false;
        $article->created_by = Auth::user()->id;
        $article->updated_by = Auth::user()->id;
        $article->save();

        $article->tags()->sync($request->tags);
        $article->categories()->sync($request->categories);

        $articles = Article::all();
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::with('tags', 'categories')->where('id', $id)->first(); // return $article;
        $tags = Tag::all();
        $categories = Category::all();
        return view('admin.articles.edit', compact(['article', 'tags', 'categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'subtitle' => 'required',
            'body' => 'required',
            'image' => 'required'
        ]);

        $article = Article::find($id);

        if ($request->hasFile('image')) {
            $fileName  = $request->image->getClientOriginalName();
            if ($article->image) {
                Storage::delete('/storage/app/public/images' . $article->image);
            }
            $request->image->storeAs('images', $fileName, 'public');
            $article->image = $fileName;
        }

        $article->title = $request->title;
        $article->subtitle = $request->subtitle;
        $article->body = $request->body;
        $article->status = $request->status ? $request->status : false;
        $article->updated_by = Auth::user()->id;
        $article->tags()->sync($request->tags);
        $article->categories()->sync($request->categories);

        $article->save();

        return redirect(route('article.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Article::where('id', $id)->delete();

        $articles = Article::all();
        return view('admin.articles.index', compact('articles'));
    }
}

app/Http/Controllers/User/ArticleController.php
<?php

namespace App\Http\Controllers\User;

use App\Article;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function article(Article $article)
    {
        return view('user.article', compact('article'));
    }
}

resources/views/admin/articles/article.blade.php
@extends('admin.layouts.app')

@section('navHead')
<a href="{{ route('article.index') }}">
    <h3>Articles
    </h3>
</a>
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form role="form" method="POST" action="{{ route('article.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <div class="card-header">
                        <h3 class="card-title">
                            Write an article
                            <small>| What is in your mind?</small>
                        </h3>
                    </div>
                    <div class="card-body pad">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Article title</label>
                                    <input type="text" class="form-control" name="title" id="title" placeholder="Title">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Article subtitle</label>
                                    <input type="text" class="form-control" name="subtitle" id="subtitle"
                                        placeholder="Subtitle">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="exampleInputFile">Article image</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="image" id="image">
                                            <label class="custom-file-label" for="image">Choose image</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="exampleInputFile">Publish Article</label>
                                    <div class="form-check">
                                        <input type="checkbox" value="1" class="form-check-input" name="status"
                                            id="status">
                                        <label class="form-check-label" for="status">Publish</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Categories</label>
                                    <select class="select2" name="categories[]" id="categories" multiple="multiple"
                                        data-placeholder="Select a category" style="width: 100%;">
                                        <option value="">-</option>
                                        @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Tags</label>
                                    <select class="select2" name="tags[]" id="tags" multiple="multiple"
                                        data-placeholder="Select a tag" style="width: 100%;">
                                        <option value="">-</option>
                                        @foreach ($tags as $tag)
                                        <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <textarea class="textarea" placeholder="Place some text here" name="body" id="body"
                                style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                        </div>
                        <div class="card-footer">
                            <input type="submit" class="btn btn-primary" value="Post">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('footer')
<script src="{{ asset('admin/plugins/select2/js/select2.full.min.js') }}"></script>
<script src="{{ asset('admin/plugins/select2/js/select2.min.js') }}"></script>
<script>
    $(function () {
      $('.select2').select2()
    })
</script>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app')

@section('navHead')
<a href="{{ route('article.index') }}">
    <h3>Articles
    </h3>
</a>
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form role="form" method="POST" action="{{ route('article.update', $article->id) }}"
            enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-12">
                    <div class="card-header">
                        <h3 class="card-title">
                            Update article#{{ $article->id }}
                            <small>| What is in your mind?</small>
                        </h3>
                    </div>
                    <div class="card-body pad">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Article title</label>
                                    <input type="text" class="form-control" value="{{ $article->title }}" name="title"
                                        id="title" placeholder="Title">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Article subtitle</label>
                                    <input type="text" class="form-control" value="{{ $article->subtitle }}"
                                        name="subtitle" id="subtitle" placeholder="Subtitle">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="exampleInputFile">Article image</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" value="{{ $article->image }}"
                                                name="image" id="image">
                                            <label class="custom-file-label" for="image">Choose image</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="exampleInputFile">Publish Article</label>
                                    <div class="form-check">
                                        <input type="checkbox" value="1" class="form-check-input" @if ($article->status
                                        == 1)
                                        checked
                                        @endif name="status" id="status">
                                        <label class="form-check-label" for="status">Publish</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Categories</label>
                                    <select class="select2" name="categories[]" id="categories" multiple="multiple"
                                        data-placeholder="Select a category" style="width: 100%;">
                                        <option value="">-</option>
                                        @foreach ($categories as $category)
                                        <option value="{{ $category->id }}" @foreach ($article->categories as
                                            $articleCategory)
                                            @if ($category->id == $articleCategory->id)
                                            selected
                                            @endif
                                            @endforeach
                                            >{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Tags</label>
                                    <select class="select2" name="tags[]" id="tags" multiple="multiple"
                                        data-placeholder="Select a tag" style="width: 100%;">
                                        <option value="">-</option>
                                        @foreach ($tags as $tag)
                                        <option value="{{ $tag->id }}" @foreach ($article->tags as $articleTag)
                                            @if ($tag->id == $articleTag->id)
                                            selected
                                            @endif
                                            @endforeach
                                            >{{ $tag->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <textarea class="textarea" placeholder="Place some text here" name="body" id="body"
                                style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ $article->body }}</textarea>
                        </div>
                        <div class="card-footer">
                            <input type="submit" class="btn btn-warning" value="Update">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('footer')
<script src="{{ asset('admin/plugins/select2/js/select2.full.min.js') }}"></script>
<script src="{{ asset('admin/plugins/select2/js/select2.min.js') }}"></script>
<script>
    $(function () {
      $('.select2').select2()
    })
</script>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app')

@section('head')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}} ">
<link rel="stylesheet" href="{{ asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}} ">
@endsection

@section('navHead')
<h3>Articles
    @can('articles.create', Auth::user())
    <a href="{{ route('article.create') }}"><small>| Create new.</small></a>
    @endcan
</h3>
@endsection

@section('content')
<div class="card">
    <!-- /.card-header -->
    <div class="card-body">
        <table id="articleTable" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th>Title</th>
                    <th>Subtitle</th>
                    <th>Is published</th>
                    <th>Posted by</th>
                    <th>Updated by</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($articles as $article)
                <tr>
                    <td>{{ $article->id }}</td>
                    <td>{{ $article->title }}</td>
                    <td>{{ $article->subtitle }}</td>
                    <td>
                        @if ($article->status == 1)
                        Published
                        @else
                        Not published
                        @endif
                    </td>
                    <td>{{ $article->userCreated->name }}</td>
                    <td>{{ $article->userUpdated->name }}</td>
                    <td><a href="{{ route('article.edit', $article->id) }}"><span
                                class="oi oi-external-link"></span></a></td>
                    <td>
                        @can('articles.delete', Auth::user())
                        @if (Auth::user()->id == $article->userCreated->id)
                        <form id="deleteForm{{$article->id}}" method="POST"
                            action="{{ route('article.destroy', $article->id) }}" style="display: none">
                            @csrf
                            @method('DELETE')
                        </form>
                        <a href="#"
                            onclick="event.preventDefault();if(confirm('Are you sure to delete Article#{{$article->id}}?')){document.getElementById('deleteForm{{$article->id}}').submit();}"><span
                                class="oi oi-trash"></span></a>
                        @endif
                        @endcan
                    </td>
                </tr>
                @empty
                <tr>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <th>S.No</th>
                    <th>Title</th>
                    <th>Subtitle</th>
                    <th>Is published</th>
                    <th>Posted by</th>
                    <th>Updated by</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>
@endsection

@section('footer')
<!-- DataTables -->
<script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script>
    $(function () {
      $("#articleTable").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
    });
</script>
@endsection