routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'User'], function () {
    Route::get('/', 'HomeController@index')->name('welcome');

    Route::get('/article/{article?}', 'ArticleController@article')->name('article');

    Route::get('/article/tag/{tag?}', 'HomeController@tag')->name('tag');

    Route::get('/article/category/{category?}', 'HomeController@category')->name('category');
});

Route::group(['namespace' => 'Admin'], function () {
    Route::get('administration/home', 'HomeController@index')->name('admin.home');

    Route::resource('administration/user', 'UserController');

    Route::resource('administration/adminUser', 'AdminUserController');

    Route::resource('administration/role', 'RoleController');

    Route::resource('administration/article', 'ArticleController');

    Route::resource('administration/tag', 'TagController');

    Route::resource('administration/category', 'CategoryController');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = [
        'name'
    ];

    public function userCreated()
    {
        return $this->belongsTo('App\User', 'created_by');
    }

    public function userUpdated()
    {
        return $this->belongsTo('App\User', 'updated_by');
    }

    public function articles()
    {
        return $this->belongsToMany('App\Article', 'article_tags')->orderBy('created_at', 'desc')->paginate(3);
    }

    public function getRouteKeyName()
    {
        return 'id';
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class TagController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::forUser(Auth::user())->allows('articles.create')) {
            $tags = Tag::all();
            return view('admin.tags.index', compact('tags'));
        }
        return redirect(route('admin.home'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::forUser(Auth::user())->allows('articles.create')) {
            return view('admin.tags.tag');
        }
        return redirect(route('admin.home'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ]);

        $tag = new Tag();
        $tag->name = $request->name;
        $tag->created_by = Auth::user()->id;
        $tag->updated_by = Auth::user()->id;
        $tag->save();

        $tags = Tag::all();
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::forUser(Auth::user())->allows('articles.create')) {
            $tag = Tag::where('id', $id)->first();
            return view('admin.tags.edit', compact('tag'));
        }
        return redirect(route('admin.home'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
        ]);

        $tag = Tag::find($id);

        $tag->name = $request->name;
        $tag->updated_by = Auth::user()->id;

        $tag->save();

        return redirect(route('tag.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::where('id', $id)->delete();

        $tags = Tag::all();
        return view('admin.tags.index', compact('tags'));
    }
}

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.app')

@section('navHead')
<a href="{{ route('tag.index') }}">
    <h3>Tags
    </h3>
</a>
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form role="form" action="{{ route('tag.update', $tag->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-12">

                    <div class="card-header">
                        <h3 class="card-title">
                            Update tag#{{ $tag->id }}
                            <small>| What is in your mind?</small>
                        </h3>
                    </div>
                    <div class="card-body pad">
                        <div class="box-body">
                            <div class="col-lg-offset-4 col-lg-6">
                                <div class="form-group">
                                    <label>Tag name</label>
                                    <input type="text" class="form-control" value="{{ $tag->name }}" name="name"
                                        id="name" placeholder="Name">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer form-group">
                        <input type="submit" class="btn btn-warning" value="Update">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.app')

@section('head')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}} ">
<link rel="stylesheet" href="{{ asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}} ">
@endsection

@section('navHead')
<h3>Tags
    <a href="{{ route('tag.create') }}"><small>| Create new.</small></a>
</h3>
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <table id="tagTable" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th>Name</th>
                    <th>Created by</th>
                    <th>Updated by</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($tags as $tag)
                <tr>
                    <td>{{ $tag->id }}</td>
                    <td>{{ $tag->name }}</td>
                    <td>{{ $tag->userCreated->name }}</td>
                    <td>{{ $tag->userUpdated->name }}</td>
                    <td><a href="{{ route('tag.edit', $tag->id) }}"><span class="oi oi-external-link"></span></a></td>
                    <td>
                        @if (Auth::user()->id == $tag->userCreated->id)
                        <form id="deleteForm{{$tag->id}}" method="POST" action="{{ route('tag.destroy', $tag->id) }}"
                            style="display: none">
                            @csrf
                            @method('DELETE')
                        </form>
                        <a href="#"
                            onclick="event.preventDefault();if(confirm('Are you sure to delete Tag#{{$tag->id}}?')){document.getElementById('deleteForm{{$tag->id}}').submit();}"><span
                                class="oi oi-trash"></span></a>
                        @endif
                    </td>
                </tr>
                @empty
                <tr>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <th>S.No</th>
                    <th>Name</th>
                    <th>Created by</th>
                    <th>Updated by</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>
@endsection

@section('footer')
<!-- DataTables -->
<script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script>
    $(function () {
      $("#tagTable").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
    });
</script>
@endsection

resources/views/admin/tags/tag.blade.php
@extends('admin.layouts.app')

@section('navHead')
<a href="{{ route('tag.index') }}">
    <h3>Tags
    </h3>
</a>
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form role="form" action="{{ route('tag.store') }}" method="POST">
            @csrf
            <div class="row">
                <div class="col-md-12">

                    <div class="card-header">
                        <h3 class="card-title">
                            Create a new tag
                            <small>| What is in your mind?</small>
                        </h3>
                    </div>
                    <div class="card-body pad">
                        <div class="box-body">
                            <div class="col-lg-offset-4 col-lg-6">
                                <div class="form-group">
                                    <label>Tag name</label>
                                    <input type="text" class="form-control" name="name" id="name" placeholder="Name">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer form-group">
                        <input type="submit" class="btn btn-primary" value="Create">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection